// <autogenerated>
// This code was generated by a tool. Any changes made manually will be lost
// the next time this code is regenerated.
// </autogenerated>
using System;   

public class MyClass
{

	public static int Item0 { get; set; }
	public static int Item1 { get; set; }
	public static int Item2 { get; set; }

   public static void Main()
   {
      Console.WriteLine("Test Template");
   }
}
